import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import StoreProvider from "./storeProvider";
import { Appbar } from "@/components/AppBar";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`antialiased`}
        >
          <Appbar />

          {children}
          <ToastContainer hideProgressBar position="bottom-right" />
        </body>
      </StoreProvider>
    </html>
  );
}
